# Generated by Django 3.0.3 on 2020-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0002_auto_20200616_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='href',
        ),
        migrations.RemoveField(
            model_name='rawmaterials',
            name='place_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedetails',
            name='href',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedetails',
            name='place_id',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
