# Generated by Django 3.0.3 on 2020-06-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0005_remove_storedetails_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('rawMaterial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stwms_app.RawMaterials')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stwms_app.StoreDetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
