# Generated by Django 3.0.3 on 2020-06-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0007_auto_20200617_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name_plural': 'Transaction History'},
        ),
        migrations.AlterModelOptions(
            name='travelhistory',
            options={'verbose_name_plural': 'Travel History'},
        ),
        migrations.AlterModelOptions(
            name='truckdetails',
            options={'verbose_name_plural': 'Truck Details'},
        ),
    ]
