# Generated by Django 3.0.3 on 2020-06-16 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stwms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialbatches',
            options={'verbose_name_plural': 'Raw Material Batches'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterials',
            options={'verbose_name_plural': 'Raw Material Details'},
        ),
        migrations.AlterModelOptions(
            name='storedetails',
            options={'verbose_name_plural': 'Store Details'},
        ),
        migrations.AlterModelOptions(
            name='storeinventory',
            options={'verbose_name_plural': 'Store Inventory'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='warehouseinventory',
            options={'verbose_name_plural': 'Warehouse Inventory'},
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='href',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='place_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='unitsSold',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
