# Generated by Django 3.0.3 on 2020-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0003_auto_20200616_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedetails',
            name='store_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
