# Generated by Django 3.0.3 on 2020-06-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0006_auto_20200616_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckDetails',
            fields=[
                ('truck_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('truck_owner', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stwms_app.RawMaterialBatches')),
                ('destStore_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stwms_app.StoreDetails')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stwms_app.TruckDetails')),
            ],
        ),
    ]
