# Generated by Django 3.0.3 on 2020-06-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0008_auto_20200618_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='hash',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
