# Generated by Django 3.0.3 on 2020-06-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0009_transactionhistory_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromStore_id', models.CharField(max_length=3)),
                ('rawMaterial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stwms_app.RawMaterials')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stwms_app.StoreDetails')),
            ],
            options={
                'verbose_name_plural': 'Raw Materials Requests',
            },
        ),
    ]
