# Generated by Django 3.0.3 on 2020-06-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0010_rawmaterialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialrequest',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
