# Generated by Django 3.0.3 on 2020-06-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0011_rawmaterialrequest_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterials',
            options={'ordering': ['rawMaterial_id'], 'verbose_name_plural': 'Raw Material Details'},
        ),
        migrations.AlterModelOptions(
            name='storeinventory',
            options={'ordering': ['storeId', 'rawMaterial_id'], 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterField(
            model_name='rawmaterialrequest',
            name='fromStore_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromStore', to='stwms_app.StoreDetails'),
        ),
        migrations.AlterField(
            model_name='rawmaterialrequest',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedStore', to='stwms_app.StoreDetails'),
        ),
        migrations.DeleteModel(
            name='WarehouseInventory',
        ),
    ]
