# Generated by Django 3.0.3 on 2020-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0013_auto_20200622_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='request_id',
        ),
        migrations.AddField(
            model_name='rawmaterialrequest',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
