# Generated by Django 3.0.3 on 2020-06-23 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0016_auto_20200623_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='hash',
        ),
        migrations.AddField(
            model_name='rawmaterialbatches',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialbatches',
            name='hash',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
