# Generated by Django 3.0.3 on 2020-06-24 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0019_auto_20200623_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelhistory',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='travelhistory',
            name='destStore_id',
        ),
        migrations.AddField(
            model_name='rawmaterialrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialrequest',
            name='truck',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='stwms_app.TruckDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='fromStore_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='travelFromStore', to='stwms_app.StoreDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='toStore_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='travelToStore', to='stwms_app.StoreDetails'),
            preserve_default=False,
        ),
    ]
