# Generated by Django 3.0.3 on 2020-06-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0020_auto_20200624_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='status',
        ),
    ]
