# Generated by Django 3.0.3 on 2020-06-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0021_remove_rawmaterialrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='truck',
        ),
        migrations.AddField(
            model_name='rawmaterialrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
