# Generated by Django 3.0.3 on 2020-06-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0022_auto_20200624_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialrequest',
            name='truck',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
