# Generated by Django 3.0.3 on 2020-06-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0023_rawmaterialrequest_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='status',
        ),
    ]
