# Generated by Django 3.0.3 on 2020-06-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0024_remove_rawmaterialrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='truck',
        ),
    ]
