# Generated by Django 3.0.3 on 2020-06-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stwms_app', '0026_auto_20200624_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialrequest',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stwms_app.TruckDetails'),
        ),
    ]
